const T={en:{
nav:{about:"About",research:"Research",stats:"Stats",scam:"SCAM",method:"Method",stack:"Stack",contact:"Contact"},
hero:{status:"Independent security research",sub:"I research web applications and APIs to uncover weaknesses in authentication, access control and business logic.",cta:"View research",contact:"Contact"},
metrics:{findings:"documented findings",targets:"research targets",focus:"core focus areas",writeups:"public write-ups"},
labels:{about:"ABOUT",research:"RESEARCH",stats:"SECURITY STATS",timeline:"TIMELINE",scam:"SCAM WATCH",vulns:"VULNERABILITY MATRIX",console:"RESEARCH CONSOLE",targets:"TARGETS",bounty:"BOUNTY HISTORY",method:"METHOD",stack:"STACK",contact:"CONTACT"},
about:{title:"Think like the application.",text:"Security research is less about throwing payloads at a target and more about understanding what the application assumes is true. I map those assumptions, challenge them and turn unexpected behavior into reproducible evidence.",p1h:"Observe",p1p:"Map endpoints, roles, tokens, state transitions and trust boundaries.",p2h:"Challenge",p2p:"Test what happens when the expected sequence, identity or state changes.",p3h:"Prove",p3p:"Reduce the behavior to a clean, repeatable proof and document it responsibly."},
research:{title:"Selected findings."},stats:{title:"Research at a glance.",targets:"research targets",payout:"largest listed payout",findings:"documented findings",writeups:"public write-ups",focus:"research mindset"},timeline:{title:"Research history.",zooma:"Research permission received.",moneyx:"Responsible disclosure sent.",casher:"Security findings reported."},vulns:{title:"What gets tested.",all:"ALL"},console:{title:"Talk to the terminal.",placeholder:"type a command..."},bounty:{title:"Disclosure outcomes.",target:"Target",issue:"Issue",amount:"Amount",status:"Status",offered:"offered",recorded:"payout",documented:"documented",pendingIssue:"multiple findings"},
cards:{slots:{title:"Authentication & account logic",text:"Authentication, session and account-control issues documented across the application.",rewardLabel:"Payout:"},onx:{title:"Authorization & business logic",text:"KYC, payout, balance, race-condition and WebSocket access-control findings.",rewardLabel:"Payout:"},vodka:{title:"WebSocket access control",text:"WebSocket / Centrifugo research. A personal-channel authorization issue was identified.",read:"Open research"},casher:{title:"Security findings",text:"Production credential exposure, client-side authentication key exposure and several access-control and injection points reported to Casher.",statusLabel:"Status:",status:"Report sent to Casher",finding1Label:"Exposed Production Credentials:",finding1:"Production MQTT/WebSocket credentials found in a public JavaScript bundle.",finding2Label:"Client-Side Authentication Key Exposure:",finding2:"signature_hash_key is passed to the client and used to form x-signature authentication requests.",finding3Label:"Potential IDOR / BOLA:",finding3:"API endpoints using user_id and transaction_id require server-side authorization checks.",finding4Label:"Potential MQTT Cross-Account Access:",finding4:"User-specific MQTT topics require ACL validation against access to other users' data.",finding5Label:"Potential XSS Sink:",finding5:"innerHTML is used when rendering notification content; exploitability requires additional verification."},zooma:{title:"Responsible disclosure",text:"Race conditions, IDOR, XSS and token-exposure issues reported through a responsible disclosure channel.",statusLabel:"Status:",status:"Response received",rewardLabel:"Bounty:",reward:"35,000 RUB",permissionLabel:"Research authorization:",permission:"received 23.09.2026",bountyLabel:"Bug bounty program:",bounty:"none, payments handled individually",result:"Zooma confirmed the XSS via winnerName in giveaways and stated that it is ready to pay 35,000 RUB.",position:"For the other reported items, Zooma stated that changing userID does not provide access to other users' data, verify rounds are public, the seed is disclosed only after a round is completed, and the Centrifugo JWT is the current user's client connection token."}},
read:"Read write-up",
scam:{title:"Unresolved disclosures.",note:"This table records unresolved disclosure communication only. A SCAM label is not a verified accusation; entries are based on documented contact status and are subject to update.",target:"Target",state:"Status",lastContactLabel:"Last contact:",basisLabel:"Basis:",classLabel:"Classification:",moneyx:{status:"no response · 4 days",lastContact:"26.09.2026",basis:"responsible disclosure sent; no reply received",classification:"unverified / unresolved"}},targets:{title:"Research surface.",target:"Target",state:"State",pending:"disclosure",responded:"response received"},
method:{title:"Map. Model. Break. Prove.",m1h:"Map",m1p:"Routes, APIs, parameters, roles, tokens and application state.",m2h:"Model",m2p:"Trust boundaries, assumptions and what the server actually verifies.",m3h:"Break",m3p:"Authorization, validation, concurrency, state and business logic.",m4h:"Prove",m4p:"Minimal reproduction, evidence, impact and responsible disclosure."},
stack:{title:"Tools & focus."},
contact:{title:"Let's talk security.",text:"Responsible disclosure, research collaboration or a technical question — choose a channel."},
copied:"Email copied"
},ru:{
nav:{about:"Обо мне",research:"Исследования",stats:"Статистика",scam:"SCAM",method:"Метод",stack:"Стек",contact:"Контакты"},
hero:{status:"Независимое исследование безопасности",sub:"Исследую веб-приложения и API, чтобы находить слабые места в аутентификации, контроле доступа и бизнес-логике.",cta:"Смотреть исследования",contact:"Связаться"},
metrics:{findings:"документированных находок",targets:"целей исследования",focus:"ключевых направлений",writeups:"публичных write-up"},
labels:{about:"ОБО МНЕ",research:"ИССЛЕДОВАНИЯ",stats:"СТАТИСТИКА",timeline:"ХРОНОЛОГИЯ",scam:"SCAM WATCH",vulns:"МАТРИЦА УЯЗВИМОСТЕЙ",console:"ИССЛЕДОВАТЕЛЬСКАЯ КОНСОЛЬ",targets:"ЦЕЛИ",bounty:"ИСТОРИЯ ВЫПЛАТ",method:"МЕТОД",stack:"СТЕК",contact:"КОНТАКТЫ"},
about:{title:"Думать как приложение.",text:"Исследование безопасности — это не просто отправка payload. Важно понять, какие предположения делает приложение, проверить их и превратить неожиданное поведение в воспроизводимое доказательство.",p1h:"Наблюдать",p1p:"Изучать endpoints, роли, токены, состояния и границы доверия.",p2h:"Проверять",p2p:"Менять ожидаемый порядок действий, идентичность и состояние системы.",p3h:"Доказывать",p3p:"Сводить поведение к чистому повторяемому PoC и ответственно документировать результат."},
research:{title:"Избранные находки."},stats:{title:"Исследования в цифрах.",targets:"целей исследования",payout:"максимальная указанная выплата",findings:"документированных находок",writeups:"публичных write-up",focus:"исследовательский подход"},timeline:{title:"История исследований.",zooma:"Получено разрешение на исследование.",moneyx:"Отправлено ответственное раскрытие.",casher:"Отчёт по находкам отправлен."},vulns:{title:"Что проверяется.",all:"ВСЕ"},console:{title:"Поговори с терминалом.",placeholder:"введи команду..."},bounty:{title:"Результаты раскрытий.",target:"Цель",issue:"Находка",amount:"Сумма",status:"Статус",offered:"предложено",recorded:"выплата",documented:"документировано",pendingIssue:"несколько находок"},
cards:{slots:{title:"Аутентификация и аккаунт",text:"Задокументированные проблемы аутентификации, сессий и управления аккаунтом.",rewardLabel:"Выплата:"},onx:{title:"Контроль доступа и бизнес-логика",text:"Находки в KYC, выплатах, балансах, race condition и WebSocket-доступе.",rewardLabel:"Выплата:"},vodka:{title:"Контроль доступа WebSocket",text:"Исследование WebSocket / Centrifugo. Обнаружена проблема авторизации персональных каналов.",read:"Открыть исследование"},casher:{title:"Находки безопасности",text:"Раскрытие production credentials, клиентского ключа аутентификации и потенциальные проблемы контроля доступа и XSS переданы Casher.",statusLabel:"Статус:",status:"Отчёт отправлен в Casher",finding1Label:"Exposed Production Credentials:",finding1:"Production MQTT/WebSocket credentials обнаружены в публичном JavaScript bundle.",finding2Label:"Client-Side Authentication Key Exposure:",finding2:"signature_hash_key передаётся клиенту и используется для формирования x-signature authentication-запросов.",finding3Label:"Potential IDOR / BOLA:",finding3:"API endpoints с user_id и transaction_id требуют проверки server-side authorization.",finding4Label:"Potential MQTT Cross-Account Access:",finding4:"User-specific MQTT topics требуют проверки ACL на доступ к данным других пользователей.",finding5Label:"Potential XSS Sink:",finding5:"innerHTML используется при отображении notification content; exploitability требует дополнительной проверки."},zooma:{title:"Ответственное раскрытие",text:"Race condition, IDOR, XSS и проблемы с токенами переданы через канал ответственного раскрытия.",statusLabel:"Статус:",status:"Ответ получен",rewardLabel:"Награда:",reward:"35 000 ₽",permissionLabel:"Разрешение на исследование:",permission:"получено 23.09.2026",bountyLabel:"Bug bounty программа:",bounty:"отсутствует, выплаты в индивидуальном порядке",result:"Zooma подтвердила XSS через winnerName в розыгрышах и сообщила о готовности выплатить 35 000 ₽.",position:"По остальным пунктам Zooma указала, что подмена userID не даёт доступа к чужим данным, verify-раунды публичны, seed раскрывается только после завершения раунда, а Centrifugo JWT является клиентским connection token."}},
read:"Читать write-up",
scam:{title:"Нерешённые раскрытия.",note:"Таблица фиксирует только отсутствие ответа по ответственному раскрытию. Пометка SCAM не является подтверждённым обвинением; записи основаны на зафиксированном статусе связи и могут быть обновлены.",target:"Цель",state:"Статус",lastContactLabel:"Последний контакт:",basisLabel:"Основание:",classLabel:"Классификация:",moneyx:{status:"нет ответа · 4 дня",lastContact:"26.09.2026",basis:"отправлено ответственное раскрытие; ответа нет",classification:"не подтверждено / вопрос не закрыт"}},targets:{title:"Поверхность исследования.",target:"Цель",state:"Статус",pending:"раскрытие",responded:"ответ получен"},
method:{title:"Карта. Модель. Атака. Доказательство.",m1h:"Карта",m1p:"Маршруты, API, параметры, роли, токены и состояния приложения.",m2h:"Модель",m2p:"Границы доверия, предположения и реальные проверки сервера.",m3h:"Атака",m3p:"Авторизация, валидация, конкуренция, состояния и бизнес-логика.",m4h:"Доказательство",m4p:"Минимальное воспроизведение, доказательства, воздействие и ответственное раскрытие."},
stack:{title:"Инструменты и фокус."},
contact:{title:"Поговорим о безопасности.",text:"Ответственное раскрытие, исследовательское сотрудничество или технический вопрос — выбери удобный канал."},
copied:"Почта скопирована"
}};
function val(o,k){
  if(Object.prototype.hasOwnProperty.call(o,k)) return o[k];
  return k.split('.').reduce((x,p)=>x?.[p],o);
}
const storageGet=(key,fallback)=>{try{return localStorage.getItem(key)||fallback}catch{return fallback}};
const storageSet=(key,value)=>{try{localStorage.setItem(key,value)}catch{}};
let lang=storageGet('1exbug-lang','en');
function apply(langName){
  lang=langName==='ru'?'ru':'en';
  storageSet('1exbug-lang',lang);
  document.documentElement.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach((element)=>{
    const value=val(T[lang],element.dataset.i18n);
    if(value!=null) element.textContent=value;
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((element)=>{
    const value=val(T[lang],element.dataset.i18nPlaceholder);
    if(value!=null) element.placeholder=value;
  });
  const en=document.getElementById('langEN');
  const ru=document.getElementById('langRU');
  en?.classList.toggle('active',lang==='en');
  ru?.classList.toggle('active',lang==='ru');
  en?.setAttribute('aria-pressed',lang==='en'?'true':'false');
  ru?.setAttribute('aria-pressed',lang==='ru'?'true':'false');
  document.title=lang==='ru'?'1exbug — Исследователь безопасности':'1exbug — Security Researcher';
  window.requestAnimationFrame(()=>window.ScrollTrigger?.refresh(true));
}
document.getElementById('langEN')?.addEventListener('click',()=>apply('en'));
document.getElementById('langRU')?.addEventListener('click',()=>apply('ru'));
apply(lang);
